export const ROUTES = {
  HOME: '/',
  INCOME: '/income',
  EXPENSES: '/expenses',
  PROJECTS: '/projects',
  REPORTS: '/reports',
  FIXED_EXPENSES: '/fixed-expenses',
  SAVINGS: '/savings',
  SUPPLIERS: '/suppliers',
  ATTACHMENTS: '/attachments',
  BACKUP: '/backup',
  SETTINGS: '/settings',
  LICENSE: '/settings/license',
  CONTACT: '/settings/contact',
} as const;
