export const ROUTES = {
  HOME: '/',
  INCOME: '/income',
  EXPENSES: '/expenses',
  PROJECTS: '/projects',
  REPORTS: '/reports',
  FIXED_EXPENSES: '/fixed-expenses',
  SAVINGS: '/savings',
  SUPPLIERS: '/suppliers',
  ATTACHMENTS: '/attachments',
  BACKUP: '/backup',
  SETTINGS: '/settings',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_CONTRIBUTORS: '/settings/contributors',
  SETTINGS_CATEGORIES: '/settings/categories',
  SETTINGS_OCR: '/settings/ocr',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_APPEARANCE: '/settings/appearance',
  SETTINGS_MODULES: '/settings/modules',
  LICENSE: '/settings/license',
  CONTACT: '/settings/contact',
} as const;
